spring.application.name=Cart
spring.datasource.url=jdbc:postgresql://localhost:5432/Capgemini
spring.datasource.username=postgres
spring.datasource.password=Superset@26
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8086
spring.config.import=optional:configserver:http://localhost:8888
spring.zipkin.base-url=http://localhost:9411
spring.zipkin.enabled=true

resilience4j.circuitbreaker.instances.cartService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.cartService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.cartService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cartService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cartService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.cartService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.cartService.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.cartService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.cartService.slidingWindowType=COUNT_BASED
